### ISSUE TITLE
Composer release

### ISSUE THREAD

**Issue by szepeviktor** [FreshMail/REST-API#4]
Please consider releasing this class on composer.
And adjust a little bit to make it composer-friendly.

**Comment by szepeviktor** [comment]
As in #1

**Comment by grzesiekgorczyca** [comment]
done

**Comment by zaporylie** [comment]
Package (`freshmail/rest-api`) is still missing from packagist.org.
